import LegalPageShell from '@/components/site/LegalPageShell'

export const metadata = {
  title: 'Terms of Service — ScholarshipFit',
  description: 'The terms governing your use of ScholarshipFit\u2019s AI-powered scholarship research and matching platform.',
}

export default function TermsPage() {
  return (
    <LegalPageShell
      title="Terms of Service"
      subtitle="The rules of the road for using ScholarshipFit. Please read carefully — by using the service, you agree to these terms."
      updated="7 July 2026"
    >
      <h2>1. Acceptance of terms</h2>
      <p>These Terms of Service (&ldquo;<strong>Terms</strong>&rdquo;) form a legally binding agreement between you and ScholarshipFit Ltd, a company registered in the Republic of Uzbekistan (&ldquo;<strong>ScholarshipFit</strong>&rdquo;, &ldquo;<strong>we</strong>&rdquo;, &ldquo;<strong>us</strong>&rdquo;, or &ldquo;<strong>our</strong>&rdquo;). By creating an account, accessing, or using the ScholarshipFit website or any related services (collectively, the &ldquo;<strong>Service</strong>&rdquo;), you agree to be bound by these Terms and by our <a href="/privacy">Privacy Policy</a>. If you do not agree, do not use the Service.</p>

      <h2>2. Eligibility</h2>
      <p>You must be at least 16 years old to use the Service. If you are under the age of majority in your jurisdiction, you may only use the Service with the consent and supervision of a parent or legal guardian, who agrees to be bound by these Terms on your behalf. You represent that all information you provide is accurate and up to date.</p>

      <h2>3. Your account</h2>
      <p>You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. Notify us immediately at <a href="mailto:legal@scholarshipfit.com">legal@scholarshipfit.com</a> if you suspect unauthorised access. We may suspend or terminate accounts for violations of these Terms.</p>

      <h2>4. Description of the Service</h2>
      <p>ScholarshipFit provides:</p>
      <ul>
        <li>A searchable database of source-linked scholarship records aggregated from official funder and institution websites.</li>
        <li>An AI-powered match ranking your profile against those records.</li>
        <li>An Application Readiness Score analyzing your competitiveness for a specific scholarship, optionally weighted by transcripts and essays you upload.</li>
        <li>A cabinet where you can save documents, favorites, and application status.</li>
        <li>Downloadable reports and, on paid tiers, additional advisory features.</li>
      </ul>
      <p>The Service is a <strong>research and decision-support tool</strong>. We do <strong>not</strong> guarantee admission, scholarship award, visa approval, or any specific outcome. Every scholarship record links to its official source, and you are solely responsible for verifying eligibility, deadlines, and application requirements on the official page before applying.</p>

      <h2>5. AI outputs and no-guarantee disclaimer</h2>
      <p>Match rankings, readiness scores, and advisor responses are generated by large language models (currently Anthropic Claude, provided via the Emergent LLM Gateway) applied to your inputs and our database. AI outputs are probabilistic, may contain errors, and are provided <strong>&ldquo;as is&rdquo; without warranty of any kind</strong>. You must independently verify any factual claim, deadline, eligibility criterion, or funding figure before acting on it. ScholarshipFit is not a licensed admissions counsellor, immigration adviser, financial adviser, or legal adviser.</p>

      <h2>6. Acceptable use</h2>
      <p>You agree not to, and not to permit anyone to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation.</li>
        <li>Scrape, crawl, harvest, mirror, or systematically extract data from the Service without our prior written consent.</li>
        <li>Reverse-engineer, decompile, or attempt to derive the source code of the Service.</li>
        <li>Submit false, misleading, or fraudulent information in scholarship or visa applications.</li>
        <li>Upload malware, engage in denial-of-service attacks, or otherwise interfere with the Service&rsquo;s operation.</li>
        <li>Impersonate any person or entity, or misrepresent your affiliation with any person or entity.</li>
        <li>Resell, sublicense, or otherwise commercially exploit the Service without a written B2B agreement with us.</li>
        <li>Use the Service to compete with us or to build a competing product.</li>
      </ul>

      <h2>7. Your content and licence to us</h2>
      <p>You retain all ownership rights in the content you submit to the Service, including your profile, uploaded transcripts, essays, and any messages (&ldquo;<strong>User Content</strong>&rdquo;). You grant us a worldwide, non-exclusive, royalty-free licence to host, store, process, transmit, and display your User Content solely to operate and improve the Service. We will not sell your User Content or use it to train third-party AI models.</p>
      <p>You represent that you own or have all necessary rights to your User Content and that its submission does not violate any third-party rights or applicable laws.</p>

      <h2>8. Our intellectual property</h2>
      <p>The Service, including its design, source code, database compilation, AI prompts, branding, and all other elements other than User Content, is owned by ScholarshipFit or its licensors and is protected by copyright, trademark, and other intellectual-property laws. We grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the Service for your personal, non-commercial scholarship research. All other rights are reserved.</p>

      <h2>9. Paid features and subscriptions</h2>
      <p>Certain features of the Service are offered on a paid subscription basis. When you subscribe, you authorise us (and our payment processor) to charge your payment method on the recurring interval you selected until you cancel. Prices, billing intervals, and features are described on the <a href="/pricing">Pricing</a> page. Taxes may apply based on your billing address.</p>
      <p>Refunds are handled per our <a href="/refunds">Refund Policy</a> (14-day money-back guarantee for new subscribers on their first paid subscription cycle).</p>

      <h2>10. Cancellation and termination</h2>
      <p>You may cancel your subscription at any time from your account settings; cancellation takes effect at the end of the current billing period. We may suspend or terminate your access to the Service at our discretion if you breach these Terms, misuse the Service, or if we discontinue the Service. On termination, sections that by their nature should survive (including sections 5-8, 10-15) will continue to apply.</p>

      <h2>11. Third-party links and services</h2>
      <p>Scholarship records include links to third-party websites operated by funders and universities. We do not control those sites, do not endorse their content, and are not responsible for their availability, accuracy, or practices. Your use of any third-party site is subject to that site&rsquo;s own terms and privacy policies.</p>

      <h2>12. Disclaimer of warranties</h2>
      <p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR THAT ANY DEFECT WILL BE CORRECTED. WE MAKE NO REPRESENTATION OR WARRANTY REGARDING THE ACCURACY, COMPLETENESS, RELIABILITY, OR USEFULNESS OF ANY AI OUTPUT OR SCHOLARSHIP INFORMATION PROVIDED BY THE SERVICE.</p>

      <h2>13. Limitation of liability</h2>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL SCHOLARSHIPFIT, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING LOST PROFITS, LOST REVENUE, LOST OPPORTUNITY, OR LOSS OF SCHOLARSHIP OR ADMISSION, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL AGGREGATE LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF OR RELATED TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE 12 MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) USD $50.</p>

      <h2>14. Indemnification</h2>
      <p>You agree to indemnify, defend, and hold harmless ScholarshipFit, its affiliates, and their respective officers, directors, employees, and agents from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&rsquo; fees) arising out of or related to (a) your use or misuse of the Service; (b) your User Content; (c) your breach of these Terms; or (d) your violation of any law or the rights of any third party.</p>

      <h2>15. Governing law and dispute resolution</h2>
      <p>These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict-of-laws principles. Any dispute arising out of or related to these Terms or the Service will be resolved exclusively by binding arbitration administered by JAMS in Wilmington, Delaware, in English, under the JAMS Streamlined Arbitration Rules. Judgment on the arbitration award may be entered in any court of competent jurisdiction. Notwithstanding the foregoing, either party may seek injunctive or equitable relief in any court of competent jurisdiction to protect its intellectual property rights.</p>
      <p><strong>Class-action waiver.</strong> You and ScholarshipFit agree that any dispute will be brought in your or our individual capacity, and not as a plaintiff or class member in any purported class, collective, or representative proceeding.</p>
      <p>If you are a consumer resident in the European Union or United Kingdom, mandatory local consumer-protection laws may apply notwithstanding the above choice of law, and you may bring proceedings in the courts of your country of residence.</p>

      <h2>16. Changes to these Terms</h2>
      <p>We may update these Terms from time to time. Material changes will be announced via email or an in-app banner at least 14 days before they take effect. Continued use of the Service after the effective date constitutes acceptance of the revised Terms.</p>

      <h2>17. Miscellaneous</h2>
      <p>These Terms, together with the Privacy Policy, Refund Policy, and any additional terms we present at the time you use a specific feature, constitute the entire agreement between you and ScholarshipFit. If any provision is held invalid or unenforceable, the remaining provisions will remain in full force and effect. Our failure to enforce any right or provision does not constitute a waiver. You may not assign these Terms without our prior written consent; we may assign them freely in connection with a corporate transaction.</p>

      <h2>18. Contact</h2>
      <p>ScholarshipFit Ltd &middot; Republic of Uzbekistan &middot; <a href="mailto:legal@scholarshipfit.com">legal@scholarshipfit.com</a></p>
    </LegalPageShell>
  )
}
