// -----------------------------------------------------------------------------
// Verified student outcomes — real people, real scholarships, real video proof.
// These videos were uploaded by the site owner with explicit student consent.
// Each entry MUST have: name, country/nationality, university, scholarship,
// video URL, quote. If any of these are missing, do not display the outcome.
// -----------------------------------------------------------------------------

export const OUTCOMES = [
  {
    slug: 'jasur-yaxshilikov',
    name: 'Jasur Yaxshilikov',
    nationality: 'Uzbekistan',
    university: 'University of Wisconsin–Madison',
    university_short: 'Wisconsin-Madison',
    country: 'United States',
    scholarship: 'Full scholarship',
    program: 'Undergraduate studies',
    video_url: 'https://customer-assets.emergentagent.com/job_stellar-fit/artifacts/lnfwf9u4_jasur-yaxshilikov-university-of-wisconsin-madison-scholarship.mov',
    video_type: 'video/quicktime',
    quote: 'ScholarshipFit shortlisted programs I would never have found manually. I applied only to the ones that actually fit.',
    duration_hint: '~1 min',
  },
  {
    slug: 'arina-pak',
    name: 'Arina Pak',
    nationality: 'Kazakhstan',
    university: 'Université de Bordeaux',
    university_short: 'Bordeaux',
    country: 'France',
    scholarship: 'Merit stipend',
    program: 'Master\u2019s program',
    video_url: 'https://customer-assets.emergentagent.com/job_stellar-fit/artifacts/z4zfmtj9_arina-pak-universite-de-bordeaux-stipend.mp4',
    video_type: 'video/mp4',
    quote: 'The fit score and gap analysis were the game-changers. I stopped writing essays for programs I could not win.',
    duration_hint: '~2 min',
  },
  {
    slug: 'shohrux-ziyodullayev',
    name: 'Shohrux Ziyodullayev',
    nationality: 'Uzbekistan',
    university: 'University of Calgary',
    university_short: 'Calgary',
    country: 'Canada',
    scholarship: 'International Entrance Scholarship',
    program: 'Undergraduate studies',
    video_url: 'https://customer-assets.emergentagent.com/job_stellar-fit/artifacts/s3lgmfm5_shohrux-ziyodullayev-university-of-calgary-scholarship.mov',
    video_type: 'video/quicktime',
    quote: 'ScholarshipFit\u2019s source-linked library saved me from wasting an entire semester on wrong applications.',
    duration_hint: '~1 min',
  },
  {
    slug: 'jurabek-maxmudov',
    name: 'Jurabek Maxmudov',
    nationality: 'Uzbekistan',
    university: 'Qatar University',
    university_short: 'Qatar University',
    country: 'Qatar',
    scholarship: 'Full tuition + living stipend',
    program: 'Undergraduate studies',
    video_url: 'https://customer-assets.emergentagent.com/job_stellar-fit/artifacts/p6u66bir_jurabek-maxmudov-qatar-university-scholarship.mov',
    video_type: 'video/quicktime',
    quote: 'The Command Center kept me organised across 5 applications. I would have missed 2 deadlines without the tracker.',
    duration_hint: '~1 min',
  },
]
